---
title: "Kaggle Titanic"
output: html_document
---

[Titanic dataset from Kaggle](https://www.kaggle.com/c/titanic)

```{r, echo=FALSE, message=FALSE}
library(ggplot2)
library(grid)
library(gridExtra)
library(scales)
library(corrplot)

library(randomForest)
library(ROCR)

setwd("~/kaggle/titanic")

# data loading
train <- read.csv("data/train.csv")
test <- read.csv("data/test.csv")
```

```
VARIABLE DESCRIPTIONS:
survival        Survival
                (0 = No; 1 = Yes)
pclass          Passenger Class
                (1 = 1st; 2 = 2nd; 3 = 3rd)
name            Name
sex             Sex
age             Age
sibsp           Number of Siblings/Spouses Aboard
parch           Number of Parents/Children Aboard
ticket          Ticket Number
fare            Passenger Fare
cabin           Cabin
embarked        Port of Embarkation
                (C = Cherbourg; Q = Queenstown; S = Southampton)

SPECIAL NOTES:
Pclass is a proxy for socio-economic status (SES)
 1st ~ Upper; 2nd ~ Middle; 3rd ~ Lower

Age is in Years; Fractional if Age less than One (1)
 If the Age is Estimated, it is in the form xx.5

With respect to the family relation variables (i.e. sibsp and parch)
some relations were ignored.  The following are the definitions used
for sibsp and parch.

Sibling:  Brother, Sister, Stepbrother, or Stepsister of Passenger Aboard Titanic
Spouse:   Husband or Wife of Passenger Aboard Titanic (Mistresses and Fiances Ignored)
Parent:   Mother or Father of Passenger Aboard Titanic
Child:    Son, Daughter, Stepson, or Stepdaughter of Passenger Aboard Titanic

Other family relatives excluded from this study include cousins,
nephews/nieces, aunts/uncles, and in-laws.  Some children travelled
only with a nanny, therefore parch=0 for them.  As well, some
travelled with very close friends or neighbors in a village, however,
the definitions do not support such relations.
```

#### Summary of training data:

```{r, echo=FALSE}
str(train)
```

### Basic Explorative Analysis

```{r, echo=FALSE, warning=FALSE}
# convert to factors
train$Survived <- as.factor(train$Survived)
train$Pclass <- as.factor(train$Pclass)

# scatterhist plot based on https://gist.github.com/mkuhn/5434709
g_legend<-function(a.gplot){
    tmp <- ggplot_gtable(ggplot_build(a.gplot))
    leg <- which(sapply(tmp$grobs, function(x) x$name) == "guide-box")
    legend <- tmp$grobs[[leg]]
    return(legend)
}

# simple plots
ageFare <- qplot(Age, Fare, data=train, color=Pclass, xlim=c(0,80), ylim=c(0,520))
ageHist <- qplot(data=train, Age, binwidth=1, fill=Pclass, xlim=c(0,80)) +
  theme(legend.position = "none", axis.ticks.x = element_blank(), axis.text.x = element_blank()) +
  labs(x=NULL)
fareHist <- qplot(data=train, Fare, binwidth=10, fill=Pclass, xlim=c(0,520)) +
  theme(legend.position = "none", axis.ticks.y = element_blank(), axis.text.y = element_blank()) +
  coord_flip() + labs(x=NULL)
grid.arrange(ageHist, g_legend(ageFare), ageFare + theme(legend.position = "none"), fareHist,
             nrow=2, ncol=2, widths=c(3/4,1/4), heights=c(1/5,4/5))

gSurvived <- qplot(data=train, as.factor(Survived), fill=Pclass, xlab="Survived", ylim=c(0,600)) + theme(legend.position = "none")
gSex      <- qplot(data=train, Sex, fill=Pclass, ylim=c(0,600)) + theme(legend.position = "none")
gPclass   <- qplot(data=train, as.factor(Pclass), fill=Pclass, xlab="Pclass", ylim=c(0,600))
gEmbarked <- qplot(data=train, as.factor(Embarked), fill=Pclass, xlab="Embarked", ylim=c(0,680)) + theme(legend.position = "none")
gSibSp    <- qplot(data=train, as.factor(SibSp), fill=Pclass, xlab="SibSp", ylim=c(0,680)) + theme(legend.position = "none")
gParch    <- qplot(data=train, as.factor(Parch), fill=Pclass, xlab="Parch", ylim=c(0,680))

grid.arrange(gSurvived, gSex, gPclass, gEmbarked, gSibSp, gParch, nrow=2, ncol=3)
```

```{r, echo=FALSE}
# pre-processing and clean-up

# convert to factors
train$Survived <- as.factor(train$Survived)
for (column in c("Pclass", "SibSp", "Parch")) {
  train[,column] <- as.factor(train[,column])
  test[,column]  <- as.factor(test[,column])
}

# fill empty embarked cities as "S"
train[train$Embarked == "", ]$Embarked <- "S"
train$Embarked <- droplevels(train$Embarked)
#test[test$Embarked == "", ]$Embarked <- "S"

# cut Fares in groups
# train$FareGroup <- cut(train$Fare, breaks=hist(as.numeric(train$Fare), breaks="Scott", plot=FALSE)$breaks, include.lowest = TRUE) # too skewed
fareQuantiles <- quantile(train$Fare, probs=seq(0, 1, 0.1))
train$FareQuant <- cut(train$Fare, breaks=fareQuantiles, include.lowest = TRUE)
test$FareQuant  <- cut(test$Fare, breaks=fareQuantiles, include.lowest = TRUE)

test[is.na(test$Fare),]$Fare <- mean(train[train$Pclass == 3,]$Fare)


# extract cabin letter (if available)
train$CabinLetter <- factor(gsub(" .*|[0-9]", "", train$Cabin), levels = c("", LETTERS[1:7], "T"))
test$CabinLetter <- factor(gsub(" .*|[0-9]", "", test$Cabin), levels = c("", LETTERS[1:7], "T"))
levels(test$CabinLetter)[1] <- levels(train$CabinLetter)[1] <- "NA"

# ensure identical levels for train and test
levels(train$Parch) <- levels(test$Parch) <- seq(0,9)

# remove unused columns
train <- train[,!(names(train) %in% c("PassengerId", "Name", "Ticket", "Cabin"))]

```

#### fixing missing age with random values

before fix:
```{r, echo=FALSE}
summary(train$Age) # 177 NA's

train$MissingAge <- is.na(train$Age)
```

after fix:
```{r, echo=FALSE}
# fix age
ageMin <- min(train$Age, na.rm = TRUE)
ageMax <- max(train$Age, na.rm = TRUE)
train$Age[is.na(train$Age)] <- as.integer(runif(sum(is.na(train$Age)), ageMin, ageMax))
test$Age[is.na(test$Age)] <- as.integer(runif(sum(is.na(test$Age)), ageMin, ageMax))

summary(train$Age) # 0 NA's
```

### Survival by Sex, Age, and Pclass
```{r, echo=FALSE, warning=FALSE}

gAge <- ggplot(train, aes(x=Survived, y=Age))
gAge <- gAge + geom_violin(adjust = 0.5, alpha = 0.3, width=0.5)
gAge <- gAge + geom_dotplot(binaxis='y', stackdir='center', dotsize=0.8, alpha= 0.4, binwidth = 1, position=position_jitter(width = 0.05), aes(fill=Sex, col=Sex))
gAge <- gAge + facet_grid(Pclass ~ Sex)
#gAge <- gAge + theme(legend.position = c(1, 0.3), legend.justification = c(1, 1), legend.text=element_text(size=6), legend.background = element_rect(fill=alpha('white', 0.5)))
gAge + coord_flip()

#gSex <- qplot(y = Survived, x = Sex, data = train, position="jitter", col = Sex, dotsize=0.5, alpha= 0.4) + facet_grid(. ~ Sex)
#grid.arrange(gAge + coord_flip(), gSex + ylab("") + theme(legend.position = "none"), ncol=2)
```

### Fare Distribution
```{r, echo=FALSE}
ggplot(train, aes(y = Fare, x = Pclass)) + geom_point(color="blue", alpha="0.2", position="jitter")
```

### Known Cabins in Pclass
```{r, echo=FALSE, warning=FALSE}
# plot Cabin Letters
ggplot(train, aes(y=Survived, x=CabinLetter, col = Pclass)) + geom_jitter() + facet_grid(Pclass ~ .)
```

### Correlation of Variables
```{r, echo=FALSE, warning=FALSE}
df <- with(train, data.frame(Pclass, Sex, Age, SibSp, Parch, Fare, FareQuant, Embarked, CabinLetter, MissingAge))
df[] <- lapply(df, as.integer)
corrplot(cor(df), order = "AOE")
```

### Prediction Models

#### Variable Importance

```{r, echo=FALSE, warning=FALSE}
fit <- randomForest(Survived ~ ., data = train, ntree=1000, importance=TRUE)
importance(fit)

par(mar=c(5,3,2,2)+0.1)
varImpPlot(fit, main = NULL) # or individually: varImpPlot(fit, type=1|2)
# plot(fit, log="y") # show errors

# confusion matrix
fit$confusion
```

```{r, echo=FALSE, warning=FALSE}
df <- with(train, data.frame(Survived, Pclass, Sex, Age, SibSp, Parch, Fare, FareQuant, Embarked, CabinLetter))
fit <- randomForest(Survived ~ ., data = df)


# eval predictions
OOB.votes <- predict (fit,train,type="prob")
OOB.pred <- OOB.votes[,2]
pred.obj <- prediction(OOB.pred, train$Survived)

RP.perf <- performance(pred.obj, "rec","prec")
plot (RP.perf)

ROC.perf <- performance(pred.obj, "fpr","tpr")
plot (ROC.perf)

lines (RP.perf@alpha.values[[1]],RP.perf@x.values[[1]], ylim=c(0,1))
abline(0,1)
lines (RP.perf@alpha.values[[1]],RP.perf@y.values[[1]])
lines (ROC.perf@alpha.values[[1]],ROC.perf@x.values[[1]])

```

```{r, echo=FALSE, warning=FALSE}
export <- function(filename, result) {
  result <- cbind(test$PassengerId, as.data.frame(result))
  names(result) <- c("PassengerId", "Survived")
  result$Survived <- as.numeric(result$Survived) -1
  write.table(result, filename, sep=",", row.names=FALSE)
}

#pred <- predict(fit, test)
#export("predictionForest.csv", pred)
```
